### ISSUE TITLE
Add similarity score to product cards

### ISSUE THREAD

**Issue by tylerhutcherson** [Spartee/redis-vector-search#13]
## Description
We want to help the user/shopper understand more about the VSS capabilities under the hood through this demo. One way we can do that is by exposing the "similarity score" of each product when clicking on "View Similar".

## TODO

**Backend**
- [x] In `routes.py`, write a new function and [apply to each product result](https://github.com/RedisVentures/redis-vector-search/blob/c03b36a31424ecb302c1defa05035322469185a7/app/vecsim_app/api/routes.py#L21) fetched by the redis client:
    - [x] async fetch the `Product` by primary key `product_pk`
    - [x] convert `todict()`
    - [x] convert vector distance (`p.vector_score`) into a similarity score (percentage out of 100)
    - [x] append `similarity_score` to the product dict
- [x] Change each vector based search route in `routes.py` to return a`List` of `Dict`

** Frontend**
- [x] Add another field to the `Props` [interface](https://github.com/RedisVentures/redis-vector-search/blob/c03b36a31424ecb302c1defa05035322469185a7/gui/src/views/Card.tsx#L14) for `similarity_score`
- [x] Add a new `div` [next to the product card buttons](https://github.com/RedisVentures/redis-vector-search/blob/c03b36a31424ecb302c1defa05035322469185a7/gui/src/views/Card.tsx#L93) that shows the score (`props.similarity_score`)
- [x] Make the score above as a `Chip` from [material-ui](https://mui.com/material-ui/react-chip/) with some color that pops. Chip is used in `Home.tsx` already [so you can see how it works](https://github.com/RedisVentures/redis-vector-search/blob/c03b36a31424ecb302c1defa05035322469185a7/gui/src/views/Home.tsx#L88).
