### ISSUE TITLE
Add tag based search to `Load New Products` button.

### ISSUE THREAD

**Issue by Spartee** [Spartee/redis-vector-search#5]
### Description

The demo interface can be a bit confusing when clicking **"Load New Products"** if the user has selected tags (**"Hybrid Search Attributes"**). The tags will disappear and NOT be used by the backend for filtering when the user loads a new batch of different products. This was a shortcut simply for development time, but the application would be smoother if tag (hybrid)  based search worked for both loading new products AND for the VSS capability (view similar by) as it does today.

### TODO

- [x] Edit the [load_products](https://github.com/RedisVentures/redis-vector-search/blob/c03b36a31424ecb302c1defa05035322469185a7/app/vecsim_app/api/routes.py#L23) api route in ``routes.py`` to take in the tags (`gender` and `category`) for search. You should be able to use the `Products.find(...)` function here, in place of the `Products.all_pks()` function, to filter by gender + category. You will also need to make sure the api route can accept the two new tag params (gender+category).
- [x] Add tag fields (gender + category) to URL params [in the front end that execute the HTTP call ](https://github.com/RedisVentures/redis-vector-search/blob/c03b36a31424ecb302c1defa05035322469185a7/gui/src/api.ts#L36) to load products.
- [x] Remove [front end related code](https://github.com/RedisVentures/redis-vector-search/blob/c03b36a31424ecb302c1defa05035322469185a7/gui/src/views/Home.tsx#L32) that removes those tags from the React state when a user selects ``Load New Products``.
